# Default values for helm-strapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

port: 1337

envs:
  - name: APPLICATION_NAME 
    value: "strapi"
  - name: PORT
    value: '1337'
  - name: NODE_ENV
    value: development
  - name: DATABASE_HOST
    value: 91.168.63.125
  - name: DATABASE_NAME
    value: "postgres"
  - name: DATABASE_SRV
    value: "false"
  - name: DATABASE_PORT
    value: "15123"
  - name: DATABASE_SSl
    value: "false"

image:
  repository: core.harbor.sostrats.com/atelier141/atelier141-back
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: 
  - name: harbor-atelier141-regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "public"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "sostrats-production"
  hosts:
    - host: strapi.sostrats.com
      http:
        paths: /
        pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    # cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 126Mi 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
